### PR TITLE
Updates to text to avoid misgendering/deadnaming Danielle Navarro

### PR DESCRIPTION
**Pull request by ekothe**
As per the pull request on lsj-data these updates and an attempt to avoid misgendering Danielle Navarro throughout the textbook. Updates to the screenshots of the parenthood.csv regression/correlation will also required in order to complete this change.

### CODE REVIEW

**Comment by ekothe** [comment]
The following figures require update as part of this pull request

- [ ] 12.5
- [ ] 12.8
- [ ] 12.9
- [ ] 12.10
- [ ] 12.13
- [ ] 12.14
- [ ] 12.15
- [ ] 12.16
- [ ] 12.23
- [ ] 12.24

**Comment by davidfoxcroft** [comment]
Hi Emily, thanks for this - much appreciated. I like your changes and am happy to merge the pull request, Before I do - can I check if you have discussed / agreed these revisions with Danielle. Don't worry if you haven't - I can do it. We're also working on revising the book to the latest version of jamovi and this will take a couple more months. Your changes will make it into this next revision, to be available on the lsj website early next year. Best. David

**Comment by ekothe** [comment]
@davidfoxcroft, I've chatted about this with Dani in general terms but not gone through the specifics. I tried to put different categories of changes in difference commits so they're easier to accept in pieces.

May need discussion:
- Commit 8bd7e8f : removes the explanatory footnote in Chapter 2 and lists Dani's self-identified gender as "female" - she may wish to review this one in in case she wants to keep some kind of explanation here
- Commit 6a3058c: this relates to the "missing data" example in the epilogue. I've updated it to be third person because the imputation uses gender and so changing the name has other flow on effects. Another option would be to add an additional grouping variable that could be used in it's place. 
- Commit e8d5165 changes an example person to "Tim" - TBH I was being lazy here because it was an abstract example and I didn't want to do a thorough pronoun search. I've actually got a WIP with this section updated to "Dani" and the pronouns corrected according.

Easy to accept
- Commit 30a5848 and 0016c93: change her name throughout the preface to "Danielle Navarro"
- Commit d749b89 and 4ee7b58: update examples to use "Dani" in variable names (which I have discussed with her)

**Comment by davidfoxcroft** [comment]
Thanks - that's helpful. I'll work through over next few weeks as we update to next version. Much appreciated.
David

**Review by davidfoxcroft — APPROVED** [review]
Helpful work from @ekothe to update text to avoid misgendering / deadnaming Danielle Navarro. Approve merging these changes and will be updated to lsj pdf version on the lsj website when we update to next version also incorporating updates to latest version of jamovi (2.2)

**Pull request merged**
